In [ ]:
%matplotlib inline


# Markov chains

Here we look at how to formulate expected threat in terms of a Markov chain.
First watch the video


..  youtube:: 5ESij-MDKl4
   :width: 640
   :height: 349


In [1]:
import numpy as np

## Setting up the matrix
We first set up the pass matrix *A* and the goal vector *g*.



Probability of scoring:
Midfield: 0.05
Box: 0.15
Wing: 0.05

Matrix represents the probability of moving from one state (Box, Wing, Goal) to another. 

In [2]:
#Pass matrix
A = np.matrix([[0.25, 0.20, 0.1], [0.1, 0.25, 0.2],[0.1, 0.1, 0.25]])
#Goal vector
g = np.transpose(np.matrix([0.05, 0.15, 0.05]))

In [4]:
A

matrix([[0.25, 0.2 , 0.1 ],
        [0.1 , 0.25, 0.2 ],
        [0.1 , 0.1 , 0.25]])

In [5]:
g

matrix([[0.05],
        [0.15],
        [0.05]])

## Linear algebra method

Here we solve *(I-A)xT = g*



The equations being solved are essentially: 

1. 0.75x1 - 0.2x2 - 0.1x3 = 0.05
2. -0.1x1 + 0.75x2 - 0.2x3 = 0.15
3. -0.1x1 - 0.1x2 + 0.75x3 = 0.05

In [18]:
#matrix by which the original matrix has been multiplied
print(np.identity(3))


xT1 = np.linalg.solve(np.identity(3) - A,g)


print(np.identity(3) - A,g)


print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.75 -0.2  -0.1 ]
 [-0.1   0.75 -0.2 ]
 [-0.1  -0.1   0.75]] [[0.05]
 [0.15]
 [0.05]]
Expected Threat
Central, Box, Wing
[[0.14991763 0.25205931 0.12026359]]


## Iterative method

Here we iterate xT' = A xT + g
to update through each move of the ball



In [11]:
xT2=np.zeros((3,1))            
for t in range(10):
   print(np.matmul(A,xT2) + g)
   xT2 = np.matmul(A,xT2) + g

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT2))

[[0.05]
 [0.15]
 [0.05]]
[[0.0975]
 [0.2025]
 [0.0825]]
[[0.123125]
 [0.226875]
 [0.100625]]
[[0.13621875]
 [0.23915625]
 [0.11015625]]
[[0.14290156]
 [0.24544219]
 [0.11507656]]
[[0.14632148]
 [0.24866602]
 [0.11760352]]
[[0.14807393]
 [0.25031936]
 [0.11889963]]
[[0.14897232]
 [0.25116716]
 [0.11956424]]
[[0.14943293]
 [0.25160187]
 [0.11990501]]
[[0.14966911]
 [0.25182476]
 [0.12007973]]
Expected Threat
Central, Box, Wing
[[0.14966911 0.25182476 0.12007973]]


## Simulation method

Here we simulate *num_sim* possessions, starting from each of the three areas.



In [13]:
num_sims=1000
xT3=np.zeros(3) 

description = {0: 'Central', 1: 'Wing', 2: 'Box' }

for i in range(3):
    num_goals = 0

    print('---------------')
    print('Start from ' + description[i] )
    print('---------------')

    for n in range(num_sims):
        
        ballinplay=True
        #Initial state is i
        s = i
        describe_possession=''
        
        while ballinplay:
            r=np.random.rand()
            
            # Make commentary text
            describe_possession = describe_possession + ' - ' + description[s]
            
            
            #Cumulative sum of in play probabilities
            c_sum=np.cumsum(A[s,:])
            new_s = np.sum(r>c_sum)  
            if new_s>2:
                #Ball is either goal or out of play
                ballinplay=False
                if r < g[s] + c_sum[0,2]:
                    #Its a goal!
                    num_goals = num_goals + 1
                    describe_possession = describe_possession + ' - Goal!'
                else:
                    describe_possession = describe_possession + ' - Out of play'
            s = new_s  
            
        print(describe_possession)  
            
    xT3[i] = num_goals/num_sims


print('\n\n---------------')
print('Expected Threat')
print('Central, Box, Wing')
print(xT3)

---------------
Start from Central
---------------
 - Central - Out of play
 - Central - Box - Out of play
 - Central - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Central - Out of play
 - Central - Wing - Box - Out of play
 - Central - Central - Wing - Central - Goal!
 - Central - Wing - Central - Out of play
 - Central - Box - Out of play
 - Central - Box - Out of play
 - Central - Wing - Wing - Wing - Out of play
 - Central - Out of play
 - Central - Wing - Wing - Central - Out of play
 - Central - Out of play
 - Central - Wing - Box - Wing - Out of play
 - Central - Out of play
 - Central - Central - Box - Box - Central - Goal!
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Goal!
 - Central - Out of play
 - Central - Central - Out of play
 - Central - Goal!
 - Central - Wing - Goal!
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Wing - 

Here I work through the derivation of equations for *xT*

<img src="file://../../../source/images/lesson4/DeriveMarkov1.png">

Here I outline how we write this in matrix form:

<img src="file://../../../source/images/lesson4/DeriveMarkov2.png">

